#!/usr/bin/env bash
set -euo pipefail

BASE_URL="http://10.9.9.20:4747"

COUNT="${1:-}"

# Validate argument
if [ -z "$COUNT" ]; then
  echo "Usage: $0 <number_of_memories (1-1001)>"
  exit 1
fi

if ! [[ "$COUNT" =~ ^[0-9]+$ ]] || [ "$COUNT" -lt 1 ] || [ "$COUNT" -gt 1001 ]; then
  echo "Error: argument must be an integer between 1 and 1001"
  exit 1
fi

for i in $(seq 1 "$COUNT"); do
  TIMESTAMP=$(date -Iseconds)
  CONTENT="Test memory #${i} - generated by insert-memories.sh at ${TIMESTAMP}"

  curl -s -X POST "${BASE_URL}/api/memories" \
    -H "Content-Type: application/json" \
    -d "{\"content\":\"${CONTENT}\",\"containerTag\":\"test-data\"}" > /dev/null

  if [ $((i % 10)) -eq 0 ]; then
    echo "Inserted ${i}/${COUNT}..."
  fi
done

echo "Done. Inserted ${COUNT} memories."
